apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejbca
  namespace: ejbca
spec:
  replicas: 1               # ajusta a lo que quieras mantener
  selector:
    matchLabels:
      app: ejbca
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: ejbca
    spec:
      containers:
        - name: ejbca
          image: ghcr.io/crisfint1425/ejbca@sha256:5dcb76753adef316b73df6fc70da2a2d82c7bc82694fe2d226776eff5ecd7d9e
          imagePullPolicy: Always
          ports:
            - containerPort: 8443
              protocol: TCP
          env:
            - name: TZ
              value: America/Cancun
            - name: EJBCA_DB_URL
              value: jdbc:postgresql://ejbca-pg-rw.ejbca.svc.cluster.local:5432/ejbca
            - name: EJBCA_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ejbca-pg-app
                  key: username
            - name: EJBCA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ejbca-pg-app
                  key: password
            - name: EJBCA_ADMIN_USERNAME
              value: superadmin
            - name: EJBCA_ADMIN_PASSWORD
              value: Admin#2025
          readinessProbe:
            httpGet:
              path: /
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: ejbca-p11
              mountPath: /opt/keyfactor/ejbca/conf/ejbca.properties
              subPath: ejbca.properties
              readOnly: true
            - name: ejbca-p11
              mountPath: /opt/keyfactor/ejbca/conf/web.properties
              subPath: web.properties
              readOnly: true
      volumes:
        - name: ejbca-p11
          configMap:
            name: ejbca-p11

