apiVersion: v1
data:
  password: Q2w0djN0M3dzdCoq
  username: ZWpiY2E=
kind: Secret
metadata:
  creationTimestamp: "2025-11-09T03:33:18Z"
  name: ejbca-pg-app
  namespace: ejbca
  resourceVersion: "39693"
  uid: d64c7faf-c756-4a1d-9f0a-06c3dbcdd78e
type: Opaque
